### ISSUE TITLE
Single row items are too tall

### ISSUE THREAD

**Issue by nchapman** [mozilla/chronicle#297]
![screen shot 2015-02-06 at 10 20 18 am](https://cloud.githubusercontent.com/assets/3095/6084880/ca934804-ade9-11e4-8b6a-c65cc0075af7.png)

These should ~10px of padding top and bottom rather than ~20px.

**Comment by pdehaan** [comment]
Borderline related, but I believe the UI spec shows that single rows items truncate w/ ellipsis instead of wrap:

![feed](https://cloud.githubusercontent.com/assets/557895/6119748/f28f62c6-b081-11e4-8c15-60c08dbad01c.png)

vs

![chronicle_and_single_row_items_are_too_tall_ _issue__297_ _mozilla_chronicle](https://cloud.githubusercontent.com/assets/557895/6119755/08cbdb1e-b082-11e4-8f2a-b7f2ec893a16.png)
